import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import {User} from '@/lib/models'








import "./globals.css";
import Navbar from "@/components/design/Navbar";
import { currentUser } from "@clerk/nextjs/server";
import { connectDB } from "@/lib/utils";






export const metadata: Metadata = {
  title: "Ahmed Todo App",
  description: "Generated by create next app",
};

export default  async function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
// ==================================================
 const user = await currentUser()
// ========================================


 if(user){

  connectDB()

    const finduser = await User.findOne({
      Id: user.id,
      email: user.emailAddresses[0].emailAddress,

    })




    if(!finduser) {
      const createUser = await User.create({
        Id: user.id,
        username: user.firstName + ' ' + user.lastName,
        email: user.emailAddresses[0].emailAddress,
        img: user.imageUrl,
      })

      
    }

   



 }
 

  return (

     
    <ClerkProvider>
      <html lang="en">
        <body>


              
        <Navbar />
       
              {children}
          
          </body>
      </html>
    </ClerkProvider>
    
  );
}
